import = ["/usr/lib/node_modules/alacritty-themes/themes/One-Dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
style = "Regular"
